# Generated by Django 3.2.5 on 2021-07-02 19:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID пользователя Telegram')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username Telegram')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ZoomLinks',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('lec', 'Лекция'), ('prac', 'Практика')], max_length=8)),
                ('subject', models.ForeignKey(on_delete=models.SET(0), to='usersmanage.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'ZOOM ссылка',
                'verbose_name_plural': 'ZOOM ссылки',
            },
        ),
    ]
