# Generated by Django 3.2.5 on 2021-07-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomlinks',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoomlinks',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль (optional)'),
        ),
        migrations.AddField(
            model_name='zoomlinks',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка (optional)'),
        ),
    ]
