# Generated by Django 3.2.5 on 2021-07-02 19:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_auto_20210702_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество (optional)')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('lec', 'Лекция'), ('prac', 'Практика')], max_length=8)),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('subject', models.ForeignKey(on_delete=models.SET(0), to='usersmanage.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Перподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
