# Generated by Django 3.2.5 on 2021-07-02 20:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='audience_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер аудитории (optional)'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lesson_number',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1-ая пара'), ('2', '2-ая пара'), ('3', '3-яя пара'), ('4', '4-ая пара'), ('5', '5-ая пара'), ('6', '6-ая пара'), ('7', '7-ая пара')], default=1, max_length=13, verbose_name='Номер пары'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to='usersmanage.subjects', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lec', 'Лекция'), ('prac', 'Практика')], default=1, max_length=8, verbose_name='Тип пары'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='week_parity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('even', 'Четная'), ('odd', 'Нечетная')], default=1, max_length=8, verbose_name='Четность недели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lec', 'Лекция'), ('prac', 'Практика')], max_length=8, verbose_name='Тип пары'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота')], max_length=23, verbose_name='День недели (1 choice)'),
        ),
    ]
